# Generated by Django 5.2.12 on 2026-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_seedphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedphrase',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
