# Generated by Django 5.2.12 on 2026-03-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_seedphrase_is_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedphrase',
            name='phrase',
        ),
    ]
