# Generated by Django 5.2.12 on 2026-03-30 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# This migration creates a new model called 'PrivateKey' which has a one-to-one relationship with the user model and an optional foreign key to the 'SeedPhrase' model. It also includes fields to track whether the private key has been downloaded and when it was created.
class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_phrase_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed_phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_key', to='wallet.seedphrase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
